# Generated by Django 2.2 on 2020-04-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_auto_20200402_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcase',
            name='lga',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='reportcase',
            name='reportDate',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='reportcase',
            name='state',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='reportcase',
            name='ward',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='picture',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
