# Generated by Django 2.2 on 2020-04-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_auto_20200402_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='entryID',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='picture',
            field=models.URLField(blank=True, max_length=128, unique=True),
        ),
    ]
