# Generated by Django 2.2 on 2020-03-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20200331_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=120)),
                ('address', models.CharField(default='', max_length=120)),
                ('picture', models.ImageField(default='', upload_to='center/')),
                ('details', models.TextField(blank=True, null=True)),
                ('geolocation', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
