# Generated by Django 2.2 on 2020-03-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_testcenter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcenter',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='testcenter',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='testcenter',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='testcenter',
            name='details',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
