# Generated by Django 2.2 on 2020-03-30 17:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_auto_20190502_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=120)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('material', models.FileField(blank=True, null=True, upload_to='material/')),
            ],
        ),
    ]
