# Generated by Django 2.2 on 2020-03-30 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='address',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='appointment',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='preferedStateOfTest',
            field=models.CharField(choices=[('kaduna', 'Kaduna'), ('lagos', 'Lagos'), ('abuja', 'Abuja')], default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='author',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='material',
            name='description',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.FileField(blank=True, default='', null=True, upload_to='material/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='title',
            field=models.CharField(default='', max_length=120),
        ),
    ]
