# Generated by Django 2.2 on 2020-03-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_auto_20200331_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='code',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lga',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='polling_unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='sex',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='state',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='ward',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
