# Generated by Django 2.2 on 2020-03-30 19:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_auto_20200331_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='preparedDateOfTest',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
