# Generated by Django 2.2 on 2020-03-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_appointment_prepareddateoftest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='code',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
