# Generated by Django 2.2 on 2020-03-31 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_testcenter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCenter',
        ),
    ]
