# Generated by Django 2.2 on 2020-04-01 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighestQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryID', models.CharField(blank=True, default='', max_length=120)),
                ('first_Name', models.CharField(max_length=120)),
                ('middle_Name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('dob', models.DateField(max_length=120)),
                ('sex', models.CharField(max_length=120)),
                ('polling_Unit', models.CharField(max_length=120)),
                ('geolocation', models.CharField(max_length=120)),
                ('prepared_State_of_To_Be_Involved', models.CharField(choices=[('kaduna', 'Kaduna'), ('lagos', 'Lagos'), ('abuja', 'Abuja'), ('oyo', 'Oyo'), ('ogun', 'Ogun'), ('bauchi', 'Bauchi'), ('enugu', 'Enugu'), ('edo', 'Edo'), ('osun', 'Osun'), ('benue', 'Benue'), ('ekiti', 'Ekiti')], max_length=120)),
                ('prepared_Start_DateTobeInvolved', models.DateField(max_length=120)),
                ('prepared_EndDate_To_be_Involved', models.DateField(max_length=120)),
                ('prepared_Days_To_be_Involved', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('sunday', 'Sunday')], max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_Number', models.CharField(max_length=120)),
                ('date_Of_Entry', models.DateField(max_length=120)),
                ('picture', models.ImageField(blank=True, upload_to='volunteer/')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lga', to='volunteer.Lga')),
                ('profession', models.ManyToManyField(related_name='profession', to='volunteer.Profession')),
                ('qualification', models.ManyToManyField(related_name='qualification', to='volunteer.HighestQualification')),
                ('specialization', models.ManyToManyField(blank=True, related_name='specialazation', to='volunteer.Specialization')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='volunteer.State')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ward', to='volunteer.Ward')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=120)),
                ('middle_Name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('sex', models.CharField(max_length=120)),
                ('polling_Unit', models.CharField(max_length=120)),
                ('geolocation', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_Number', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('reportDate', models.DateField(max_length=120)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportCases', to='volunteer.Lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportCases', to='volunteer.State')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportCases', to='volunteer.Ward')),
            ],
        ),
    ]
