# Generated by Django 2.2 on 2020-04-01 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighestQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Lga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryID', models.CharField(blank=True, default='', max_length=120)),
                ('involvementID', models.CharField(blank=True, default='', max_length=120)),
                ('firstName', models.CharField(max_length=120)),
                ('middleName', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('dob', models.CharField(max_length=120)),
                ('sex', models.CharField(max_length=120)),
                ('pollingUnit', models.CharField(max_length=120)),
                ('geolocation', models.CharField(max_length=120)),
                ('preparedStateofToBeInvolved', models.CharField(choices=[('kaduna', 'Kaduna'), ('lagos', 'Lagos'), ('abuja', 'Abuja'), ('oyo', 'Oyo'), ('ogun', 'Ogun'), ('bauchi', 'Bauchi'), ('enugu', 'Enugu'), ('edo', 'Edo'), ('osun', 'Osun'), ('benue', 'Benue'), ('ekiti', 'Ekiti')], max_length=120)),
                ('preparedStartDateTobeInvolved', models.DateField(max_length=120)),
                ('preparedEndDateTobeInvolved', models.DateField(max_length=120)),
                ('preparedDaysTobeInvolved', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('sunday', 'Sunday')], max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phoneNo', models.CharField(max_length=120)),
                ('dateOfEntry', models.DateField(max_length=120)),
                ('picture', models.ImageField(blank=True, upload_to='volunteer/')),
                ('highestQualification', models.ManyToManyField(related_name='volunteers', to='volunteer.HighestQualification')),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='volunteer.Lga')),
                ('profession', models.ManyToManyField(related_name='volunteers', to='volunteer.Profession')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='volunteer.State')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volunteers', to='volunteer.Ward')),
            ],
        ),
    ]
