# Generated by Django 2.2 on 2020-04-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0002_highestqualification_lga_profession_state_volunteer_ward'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteer',
            old_name='dateOfEntry',
            new_name='date_Of_Entry',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='firstName',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='highestQualification',
            new_name='highest_Qualification',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='middleName',
            new_name='middle_Name',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='phoneNo',
            new_name='phone_Number',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='pollingUnit',
            new_name='polling_Unit',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='preparedDaysTobeInvolved',
            new_name='prepared_Days_To_be_Involved',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='preparedEndDateTobeInvolved',
            new_name='prepared_EndDate_To_be_Involved',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='preparedStartDateTobeInvolved',
            new_name='prepared_Start_DateTobeInvolved',
        ),
        migrations.RenameField(
            model_name='volunteer',
            old_name='preparedStateofToBeInvolved',
            new_name='prepared_State_of_To_Be_Involved',
        ),
    ]
