# Generated by Django 2.2 on 2020-04-01 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20200401_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='dob',
            field=models.DateField(max_length=120),
        ),
    ]
