# Generated by Django 2.2 on 2020-04-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0003_auto_20200402_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='ward',
            field=models.CharField(default='', max_length=120),
        ),
    ]
