# Generated by Django 2.2 on 2020-04-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_auto_20200401_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='involvementID',
        ),
    ]
