# Generated by Django 2.2 on 2020-04-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0004_volunteer_ward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='picture',
            field=models.CharField(default='', max_length=120),
        ),
    ]
