# Generated by Django 2.2 on 2020-04-01 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0005_remove_volunteer_involvementid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Expertise',
        ),
    ]
