# Generated by Django 2.2 on 2020-04-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0006_auto_20200401_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='volunteer',
            name='specialization',
            field=models.ManyToManyField(blank=True, related_name='volunteers', to='volunteer.Specialization'),
        ),
    ]
