# Generated by Django 2.2 on 2020-04-01 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0007_auto_20200401_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_Name', models.CharField(max_length=120)),
                ('middle_Name', models.CharField(max_length=120)),
                ('surname', models.CharField(max_length=120)),
                ('sex', models.CharField(max_length=120)),
                ('polling_Unit', models.CharField(max_length=120)),
                ('geolocation', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_Number', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('reportDate', models.DateField(max_length=120)),
                ('lga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportCases', to='volunteer.Lga')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportCases', to='volunteer.State')),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportCases', to='volunteer.Ward')),
            ],
        ),
    ]
