# Generated by Django 2.2 on 2020-03-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0012_auto_20190502_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('picture', models.ImageField(upload_to='center/')),
                ('details', models.TextField(blank=True, null=True)),
                ('geolocation', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
