# Generated by Django 2.2 on 2020-03-30 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0013_test_center'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test_Center',
            new_name='TestCenter',
        ),
    ]
