# Generated by Django 2.2 on 2020-03-31 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0014_auto_20200330_1627'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestCenter',
        ),
    ]
