# Generated by Django 2.2 on 2020-04-01 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=120)),
                ('description', models.CharField(default='', max_length=20)),
                ('author', models.CharField(default='', max_length=120)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('material', models.FileField(blank=True, default='', null=True, upload_to='material/')),
            ],
        ),
        migrations.CreateModel(
            name='RequestCoronaTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testRequestID', models.CharField(blank=True, default='', max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('preparedDateOfTest', models.DateField(default=django.utils.timezone.now)),
                ('time', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=10)),
                ('address', models.CharField(default='', max_length=120)),
                ('preferedStateOfTest', models.CharField(choices=[('kaduna', 'Kaduna'), ('lagos', 'Lagos'), ('abuja', 'Abuja'), ('oyo', 'Oyo'), ('ogun', 'Ogun'), ('bauchi', 'Bauchi'), ('enugu', 'Enugu'), ('edo', 'Edo'), ('osun', 'Osun'), ('benue', 'Benue'), ('ekiti', 'Ekiti')], default='', max_length=120)),
                ('dob', models.DateField(default=django.utils.timezone.now)),
                ('code', models.CharField(blank=True, max_length=2000)),
                ('sex', models.CharField(blank=True, default='', max_length=50)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('lga', models.CharField(blank=True, default='', max_length=50)),
                ('ward', models.CharField(blank=True, default='', max_length=50)),
                ('polling_unit', models.CharField(blank=True, default='', max_length=50)),
                ('note', models.TextField(blank=True, default='', null=True)),
            ],
        ),
    ]
