# Generated by Django 2.2 on 2020-04-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request_Corona_Test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestcoronatest',
            name='code',
        ),
    ]
